[package]
name = "types-are-awesome-demo"
version = "1.0.0"
authors = ["Sagnik Bhattacharya <sagnikdps@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
